.test

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   test:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     
     steps:
     - name: Checkout repository
@@ -24,49 +24,49 @@ jobs:
 
     - name: Start test environment
       run: |
-        docker compose -f docker-compose-test.yml up -d
+        docker compose --env-file .env_test -f docker-compose-test.yml up -d
         echo "Waiting for services to be healthy..."
         sleep 60
 
     - name: Check service health
       run: |
-        docker compose -f docker-compose-test.yml ps
+        docker compose --env-file .env_test -f docker-compose-test.yml ps
 
     - name: Grant superuser to geonode database user
       run: |
         # Grant SUPERUSER privilege to geonode user so it can create PostGIS extension
-        docker compose -f docker-compose-test.yml exec -T db psql -U postgres -c "ALTER USER geonode WITH SUPERUSER;"
-        docker compose -f docker-compose-test.yml exec -T db psql -U postgres -c "ALTER USER geonode_data WITH SUPERUSER;"
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T db psql -U postgres -c "ALTER USER geonode WITH SUPERUSER;"
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T db psql -U postgres -c "ALTER USER geonode_data WITH SUPERUSER;"
 
 
     - name: Run main test suite
       run: |
-        docker compose -f docker-compose-test.yml exec -T django ./test.sh || echo "MAIN_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test.sh || echo "MAIN_TESTS_FAILED=true" >> $GITHUB_ENV
       id: main_tests
 
     - name: Run API v2 tests
       run: |
-        docker compose -f docker-compose-test.yml exec -T django ./test_api_v2.sh || echo "API_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_api_v2.sh || echo "API_TESTS_FAILED=true" >> $GITHUB_ENV
       id: api_tests
 
     - name: Run CSW tests
       run: |
-        docker compose -f docker-compose-test.yml exec -T django ./test_csw.sh || echo "CSW_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_csw.sh || echo "CSW_TESTS_FAILED=true" >> $GITHUB_ENV
       id: csw_tests
 
     - name: Run integration tests
       run: |
-        docker compose -f docker-compose-test.yml exec -T django ./test_integration.sh || echo "INTEGRATION_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_integration.sh || echo "INTEGRATION_TESTS_FAILED=true" >> $GITHUB_ENV
       id: integration_tests
 
     - name: Run OAuth2 tests
       run: |
-        docker compose -f docker-compose-test.yml exec -T django ./test_oauth2.sh || echo "OAUTH_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_oauth2.sh || echo "OAUTH_TESTS_FAILED=true" >> $GITHUB_ENV
       id: oauth_tests
 
     - name: Run upload tests
       run: |
-        docker compose -f docker-compose-test.yml exec -T django ./test_upload.sh || echo "UPLOAD_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_upload.sh || echo "UPLOAD_TESTS_FAILED=true" >> $GITHUB_ENV
       id: upload_tests
 
     - name: Collect test results
@@ -124,14 +124,14 @@ jobs:
     - name: Show Django logs on failure
       if: failure()
       run: |
-        docker compose -f docker-compose-test.yml logs django
+        docker compose --env-file .env_test -f docker-compose-test.yml logs django
 
     - name: Show database logs on failure
       if: failure()
       run: |
-        docker compose -f docker-compose-test.yml logs db
+        docker compose --env-file .env_test -f docker-compose-test.yml logs db
 
     - name: Cleanup
       if: always()
       run: |
-        docker compose -f docker-compose-test.yml down -v
+        docker compose --env-file .env_test -f docker-compose-test.yml down -v
