.test corrections

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -41,32 +41,32 @@ jobs:
 
     - name: Run main test suite
       run: |
-        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test.sh || echo "MAIN_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./tests/test.sh || echo "MAIN_TESTS_FAILED=true" >> $GITHUB_ENV
       id: main_tests
 
     - name: Run API v2 tests
       run: |
-        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_api_v2.sh || echo "API_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./tests/test_api_v2.sh || echo "API_TESTS_FAILED=true" >> $GITHUB_ENV
       id: api_tests
 
     - name: Run CSW tests
       run: |
-        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_csw.sh || echo "CSW_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./tests/test_csw.sh || echo "CSW_TESTS_FAILED=true" >> $GITHUB_ENV
       id: csw_tests
 
     - name: Run integration tests
       run: |
-        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_integration.sh || echo "INTEGRATION_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./tests/test_integration.sh || echo "INTEGRATION_TESTS_FAILED=true" >> $GITHUB_ENV
       id: integration_tests
 
     - name: Run OAuth2 tests
       run: |
-        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_oauth2.sh || echo "OAUTH_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./tests/test_oauth2.sh || echo "OAUTH_TESTS_FAILED=true" >> $GITHUB_ENV
       id: oauth_tests
 
     - name: Run upload tests
       run: |
-        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./test_upload.sh || echo "UPLOAD_TESTS_FAILED=true" >> $GITHUB_ENV
+        docker compose --env-file .env_test -f docker-compose-test.yml exec -T django ./tests/test_upload.sh || echo "UPLOAD_TESTS_FAILED=true" >> $GITHUB_ENV
       id: upload_tests
 
     - name: Collect test results
